# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: react-spa-middleware

on:
  push:
    braches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
           cmd: install
           cmd: test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          auth-token: ${{secrets.npm_token}}
          registry-url: https://registry.npmjs.org/

      - uses: borales/actions-yarn@v2.3.0
        with:
           cmd: install
           cmd: publish
