# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: react-spa-middleware

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          node-version: 16
      - cmd: intall
      - cmd: test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - cmd: intall
      - cmd: publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
